"""
crucible/process/crash_recovery.py

Detects "the whole PC went down with the server" crashes -- power loss,
hard freezes, forced hardware resets -- that a live-only Watchdog can never
see, because Crucible itself was not running to witness them.

Why Watchdog alone isn't enough
--------------------------------
Watchdog (see watchdog.py) only detects a crash while its own QTimer is
polling tmux, i.e. while Crucible is open. If the entire host loses power or
hard-freezes, Crucible, tmux, and the server all die together and nobody is
left running to notice. On the next normal launch, the tmux session is
simply gone -- exactly as it would be after an ordinary, intentional Stop --
so Crucible has no way to tell "the user stopped this" apart from "the whole
machine crashed out from under this" unless it left itself a note first.

How this module closes that gap
--------------------------------
Every time a monitored instance is confirmed running, a small heartbeat file
is written recording:
  - the Linux boot id in effect at that moment (/proc/sys/kernel/random/boot_id)
  - the tmux session name
  - a state: "running" | "stopped_clean" | "crashed_handled"

A graceful Stop, or a live-witnessed Watchdog crash, updates that state
immediately. So on the *next* launch, if a heartbeat still says "running"
but the current boot id differs from the one it recorded, AND tmux confirms
no live session exists now, the only remaining explanation is that the
entire host went down (and came back up) while nobody was watching -- e.g.
the 2026-07-22 ~20:59 PDT power cut this module was written to catch.

Closing the Crucible window on purpose, or the normal "stop" flow, never
leaves a stale "running" heartbeat behind, so neither can ever be
misreported as a crash.
"""

from __future__ import annotations

import json
import os
import tempfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from ..data.instance_model import ServerInstance

STATE_DIR = Path.home() / ".config" / "crucible" / "state" / "heartbeats"

_BOOT_ID_PATH = Path("/proc/sys/kernel/random/boot_id")

RUNNING = "running"
STOPPED_CLEAN = "stopped_clean"
CRASHED_HANDLED = "crashed_handled"

_GRACEFUL_MARKERS = (b"Stopping the server", b"Stopping server", b"Saving worlds")
_DEFAULT_TAIL_BYTES = 8192
_EVIDENCE_WINDOW = 2048


def get_boot_id() -> str | None:
    """Return the current kernel boot id, or None on non-Linux/unavailable.

    This id is regenerated by the kernel on every boot (including after a
    hard crash or power loss), which is exactly the property this module
    relies on -- it is NOT a hardware/machine id and never persists across
    a reboot on its own.
    """
    try:
        text = _BOOT_ID_PATH.read_text(encoding="utf-8").strip()
        return text or None
    except OSError:
        return None


@dataclass(frozen=True)
class CrashReport:
    """One instance that appears to have gone down together with the host."""

    instance_id: str
    instance_name: str
    message: str
    log_evidence: str | None = None


class HeartbeatStore:
    """Atomic per-instance JSON heartbeat files.

    Writes use write-to-temp-then-rename, matching InstanceManager's
    registry save pattern, so a crash mid-write can only ever leave the
    PREVIOUS heartbeat in place -- never a half-written one. That is the
    fail-safe direction: worst case is one extra (already-true) crash
    report, never a swallowed one.
    """

    def __init__(self, state_dir: Path = STATE_DIR) -> None:
        self._dir = state_dir

    def _path(self, instance_id: str) -> Path:
        return self._dir / f"{instance_id}.json"

    def _write(self, instance_id: str, payload: dict) -> None:
        self._dir.mkdir(parents=True, exist_ok=True)
        path = self._path(instance_id)
        fd, tmp_name = tempfile.mkstemp(dir=str(self._dir), prefix=".tmp-")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                json.dump(payload, fh)
                fh.flush()
                os.fsync(fh.fileno())
            os.replace(tmp_name, path)
        except Exception:
            try:
                os.unlink(tmp_name)
            except OSError:
                pass
            raise

    def read(self, instance_id: str) -> dict | None:
        try:
            raw = self._path(instance_id).read_text(encoding="utf-8")
        except OSError:
            return None
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            return None
        return data if isinstance(data, dict) else None

    def mark_running(
        self, instance_id: str, tmux_session: str, boot_id: str | None = None
    ) -> None:
        self._write(
            instance_id,
            {
                "state": RUNNING,
                "boot_id": boot_id if boot_id is not None else get_boot_id(),
                "tmux_session": tmux_session,
                "updated_at": datetime.now().isoformat(),
            },
        )

    def mark_stopped_clean(self, instance_id: str) -> None:
        existing = self.read(instance_id) or {}
        self._write(
            instance_id,
            {**existing, "state": STOPPED_CLEAN, "updated_at": datetime.now().isoformat()},
        )

    def mark_crashed_handled(self, instance_id: str) -> None:
        existing = self.read(instance_id) or {}
        self._write(
            instance_id,
            {**existing, "state": CRASHED_HANDLED, "updated_at": datetime.now().isoformat()},
        )


def detect_torn_log(
    instance: ServerInstance, *, tail_bytes: int = _DEFAULT_TAIL_BYTES
) -> str | None:
    """Best-effort corroborating evidence from the instance's own log.

    Returns a short human explanation when the log ends mid-write (raw NUL
    padding) with no graceful shutdown line nearby -- the same signature
    found in fml-server-latest.log for the 2026-07-22 crash: the periodic
    "Gathering id map for writing to world save" line simply stops and is
    followed by thousands of null bytes.

    Returns None when there's nothing extra to say (log missing, looks
    graceful, or too ambiguous) -- callers must treat that as "no additional
    evidence found", never as proof the shutdown WAS clean.
    """
    log = instance.get_log_path()
    if log is None or not log.exists():
        return None
    try:
        size = log.stat().st_size
        with log.open("rb") as fh:
            fh.seek(max(0, size - tail_bytes))
            tail = fh.read()
    except OSError:
        return None

    stripped = tail.rstrip(b"\x00")
    had_null_padding = len(stripped) < len(tail)
    if any(marker in stripped[-_EVIDENCE_WINDOW:] for marker in _GRACEFUL_MARKERS):
        return None
    if had_null_padding:
        return (
            "The server log itself ends mid-write with raw null-byte padding "
            "and no shutdown message — consistent with the whole machine "
            "losing power or freezing while the world was saving."
        )
    return None


def reconcile(
    instances: list[ServerInstance],
    tmux,
    *,
    store: HeartbeatStore | None = None,
) -> list[CrashReport]:
    """Call once at app startup, after instances are loaded.

    For every instance whose last-known heartbeat still says "running" under
    a DIFFERENT boot id than the current one, AND whose tmux session is
    confirmed not running right now, report a host-level crash. Matching
    heartbeats are immediately marked "crashed_handled" so the same
    historical crash is never re-reported on a later launch.

    Callers should surface each CrashReport to the user and, for instances
    with auto_restart enabled, start the server again automatically --
    reconcile() itself never starts anything, so it stays safe to call from
    a read-only context (tests, CLI diagnostics, etc.).
    """
    store = store or HeartbeatStore()
    current_boot_id = get_boot_id()
    reports: list[CrashReport] = []

    for instance in instances:
        heartbeat = store.read(instance.id)
        if not heartbeat or heartbeat.get("state") != RUNNING:
            continue
        recorded_boot_id = heartbeat.get("boot_id")
        # Without a boot id on either side we cannot tell a reboot apart
        # from "still the same session" -- never guess.
        if not recorded_boot_id or not current_boot_id:
            continue
        if recorded_boot_id == current_boot_id:
            continue
        if tmux.is_running(instance):
            # Somehow still running (e.g. tmux itself survived) -- not a crash.
            continue

        evidence = detect_torn_log(instance)
        message = (
            f'"{instance.name}" was still marked running when Crucible last saw '
            "it, but the system has since rebooted under a different boot "
            "session without Crucible ever recording a normal stop. This points "
            "to the whole PC losing power or freezing, not a Crucible or server bug."
        )
        reports.append(
            CrashReport(
                instance_id=instance.id,
                instance_name=instance.name,
                message=message,
                log_evidence=evidence,
            )
        )
        store.mark_crashed_handled(instance.id)

    return reports
