"""
crucible/data/instance_model.py

One ServerInstance object per registered server directory.
Handles validation, start-script detection, status queries (via tmux),
and JSON serialization.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Literal


# ── Script names GTNH has used across versions ────────────────────────────────

_START_SCRIPT_NAMES = [
    "startserver-java9.sh",  # GTNH 2.8.x with java9args.txt (most common on 2.8.4)
    "startserver-java17.sh",
    "ServerStart.sh",        # 2.7+ / generated by gtnh_deploy.py
    "startserver.sh",
    "start.sh",
]


# ── Data model ────────────────────────────────────────────────────────────────

@dataclass
class ServerInstance:
    """
    Represents one registered GTNH server directory.

    Fields that map 1:1 to the JSON registry entry are stored directly.
    Status is always derived live from tmux — never cached here.
    """

    path: str                      # absolute path to server dir (string for JSON compat)
    name: str                      # display name, editable
    version: str       = "2.8.4"  # GTNH version string
    notes: str         = ""        # free-form markdown notes
    java_args: str     = "-Xms16G -Xmx16G"
    color: str         = "#7c3aed" # accent color for the future sidebar dot
    tmux_session: str  = ""        # e.g. "gtnh" or "gtnh-production"
    auto_restart: bool = False     # watchdog: auto-restart on unexpected crash
    id: str            = field(default_factory=lambda: str(uuid.uuid4()))
    created_at: str    = field(default_factory=lambda: datetime.now().isoformat())
    last_started: str | None = None

    def __post_init__(self) -> None:
        # Auto-generate session name only if caller didn't provide one
        if not self.tmux_session:
            self.tmux_session = self._derive_session_name(self.name)

    # ── Session name ──────────────────────────────────────────────────────────

    @staticmethod
    def _derive_session_name(name: str) -> str:
        """Produce a safe tmux session name from a display name."""
        slug = name.lower().replace(" ", "-").replace("_", "-")
        # strip characters tmux dislikes
        slug = "".join(c for c in slug if c.isalnum() or c == "-")
        return f"gtnh-{slug}"

    # ── Serialization ─────────────────────────────────────────────────────────

    def to_dict(self) -> dict:
        return {
            "id":           self.id,
            "path":         self.path,
            "name":         self.name,
            "version":      self.version,
            "notes":        self.notes,
            "java_args":    self.java_args,
            "color":        self.color,
            "tmux_session": self.tmux_session,
            "auto_restart": self.auto_restart,
            "created_at":   self.created_at,
            "last_started": self.last_started,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "ServerInstance":
        return cls(
            id           = d.get("id", str(uuid.uuid4())),
            path         = d["path"],
            name         = d["name"],
            version      = d.get("version", "2.8.4"),
            notes        = d.get("notes", ""),
            java_args    = d.get("java_args", "-Xms16G -Xmx16G"),
            color        = d.get("color", "#7c3aed"),
            tmux_session = d.get("tmux_session", ""),
            auto_restart = d.get("auto_restart", False),
            created_at   = d.get("created_at", datetime.now().isoformat()),
            last_started = d.get("last_started"),
        )

    # ── Validation ────────────────────────────────────────────────────────────

    def validate(self) -> list[str]:
        """
        Return a list of human-readable problems with this instance.
        Empty list = all clear.
        """
        problems: list[str] = []
        p = Path(self.path)

        if not p.exists():
            problems.append(f"Directory does not exist: {self.path}")
            return problems  # pointless to check further
        if not p.is_dir():
            problems.append(f"Path is not a directory: {self.path}")
            return problems

        if self.get_startscript() is None:
            problems.append(
                "No start script found — expected one of: "
                + ", ".join(_START_SCRIPT_NAMES)
            )

        if not (p / "mods").exists():
            problems.append("mods/ directory not found")

        if not (p / "eula.txt").exists():
            problems.append("eula.txt missing (server will refuse to start)")

        # Warn about nested jars that the mod manager cannot see
        bundled = self.get_bundled_jars()
        if bundled:
            names = ", ".join(j.name for j in bundled)
            problems.append(
                f"Nested jar(s) in mods/ subdirectory — invisible to mod manager "
                f"(must be managed manually): {names}"
            )

        return problems

    # ── Filesystem helpers ────────────────────────────────────────────────────

    @property
    def path_obj(self) -> Path:
        return Path(self.path)

    def get_startscript(self) -> Path | None:
        """
        Find the server start script, trying all known GTNH naming variants
        plus a glob fallback for unusual names.
        """
        p = self.path_obj
        for name in _START_SCRIPT_NAMES:
            candidate = p / name
            if candidate.exists():
                return candidate
        # Glob fallback — catches e.g. start-prod.sh
        for match in sorted(p.glob("start*.sh")) + sorted(p.glob("Start*.sh")):
            return match
        return None

    def get_log_path(self) -> Path | None:
        """
        Return the active log file path for this server.

        GTNH 1.7.10 (FML era) writes nearly all output to fml-server-latest.log,
        not latest.log.  latest.log exists but contains only a thin wrapper with
        a handful of lines from the most recent JVM boot.

        Resolution order (stops at the first file that exists):
          1. logs/fml-server-latest.log  — GTNH 1.7.10 primary log
          2. logs/latest.log             — vanilla / 1.12+ Forge / fallback
        """
        logs = self.path_obj / "logs"
        for name in ("fml-server-latest.log", "latest.log"):
            candidate = logs / name
            if candidate.exists():
                return candidate
        return None

    def get_mod_count(self) -> int:
        """Count enabled mods (*.jar at top level of mods/, ignoring *.jar.disabled).

        Note: jars nested inside subdirectories (e.g. mods/ic2/EJML-core-0.26.jar)
        are NOT counted here — they are not manageable via the mods tab.
        Use get_bundled_jar_count() to discover those separately.
        """
        mods = self.path_obj / "mods"
        if not mods.exists():
            return 0
        return len(list(mods.glob("*.jar")))

    def get_bundled_jars(self) -> list[Path]:
        """
        Return any .jar files nested inside mods/ subdirectories.

        These are NOT managed by ModManager (which only scans the top level).
        They cannot be enabled, disabled, or inspected through the mods tab.
        Examples: mods/ic2/EJML-core-0.26.jar (IC2 math library).
        """
        mods = self.path_obj / "mods"
        if not mods.exists():
            return []
        bundled: list[Path] = []
        for subdir in mods.iterdir():
            if subdir.is_dir():
                for jar in subdir.rglob("*.jar"):
                    bundled.append(jar)
        return bundled

    def get_world_names(self) -> list[str]:
        """
        Return names of world directories present in the server folder.
        Reads level-name from server.properties first (handles custom world names
        like 'jojo's bizarre adventure diamond is unbreakable').
        Falls back to scanning for standard world directory names.
        """
        p = self.path_obj
        found: list[str] = []

        # Primary: read level-name from server.properties
        props = p / "server.properties"
        if props.exists():
            try:
                for line in props.read_text(encoding="utf-8", errors="replace").splitlines():
                    line = line.strip()
                    if line.startswith("level-name="):
                        level_name = line.split("=", 1)[1].strip()
                        if level_name and (p / level_name).exists():
                            found.append(level_name)
                        # Also check DIM dirs alongside the level-name dir
                        nether = p / f"{level_name}_nether"
                        the_end = p / f"{level_name}_the_end"
                        if nether.exists():
                            found.append(nether.name)
                        if the_end.exists():
                            found.append(the_end.name)
                        break
            except OSError:
                pass

        if found:
            return found

        # Fallback: standard world dir names
        for candidate in ["world", "world_nether", "world_the_end"]:
            if (p / candidate).exists():
                found.append(candidate)
        return found

    # ── Display helpers ───────────────────────────────────────────────────────

    def short_id(self) -> str:
        return self.id[:8]

    def __repr__(self) -> str:
        return f"<ServerInstance name={self.name!r} session={self.tmux_session!r}>"
